# Travis CI integration for plugin test
# based on https://github.com/moodlerooms/moodle-plugin-ci/blob/master/doc/TravisFileExplained.md
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.1

env:
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli

matrix:
  exclude:
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  - moodle-plugin-ci shifter
  - moodle-plugin-ci csslint
# - moodle-plugin-ci jshint

notifications:
    slack: moodlepeers:CPibsew1aB1FWpNdPLHmJP0o